accountapp/urls.py
from django.urls import include, path
from accountapp.views import (
    AccountCreateView,
    AccountDetailView,
    AccountUpdateView,
    AccountDeleteView,
)
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accountapp"
urlpatterns = [
    path(
        "login/", LoginView.as_view(template_name="accountapp/login.html"), name="login"
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("create/", AccountCreateView.as_view(), name="create"),
    path("detail/<int:pk>", AccountDetailView.as_view(), name="detail"),
    path("update/<int:pk>", AccountUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", AccountDeleteView.as_view(), name="delete"),
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from articleapp.views import ArticleListView

urlpatterns = [
    path("", ArticleListView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accountapp.urls")),
    path("profiles/", include("profileapp.urls")),
    path("articles/", include("articleapp.urls")),
    path("comments/", include("commentapp.urls")),
    path("projects/", include("projectapp.urls")),
    path("subscribes/", include("subscribeapp.urls")),
    # path("articles/", include("articleapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import include, path
from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = "profileapp"
urlpatterns = [
    path("create/", ProfileCreateView.as_view(), name="create"),
    path("update/<int:pk>", ProfileUpdateView.as_view(), name="update"),
]

urls.py
from django.urls import include, path
from accountapp.views import (
    hello_world,
    AccountCreateView,
    AccountDetailView,
    AccountUpdateView,
    AccountDeleteView,
)
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accountapp"
urlpatterns = [
    path("hello_world/", hello_world, name="hello_world"),
    path("login/", LoginView.as_view(template_name="accountapp/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("create/", AccountCreateView.as_view(), name="create"),
    path("detail/<int:pk>", AccountDetailView.as_view(), name="detail"),
    path("update/<int:pk>", AccountUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", AccountDeleteView.as_view(), name="delete"),
]

accountapp/models.py
from django.db import models

# Create your models here.

articleapp/models.py
from django.db import models
from django.contrib.auth.models import User
from projectapp.models import Project

# Create your models here.
class Article(models.Model):
    writer = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name="article", null=True
    )
    project = models.ForeignKey(
        Project, on_delete=models.SET_NULL, related_name="article", null=True
    )

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to="article/", null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["username"].disabled = True

accountapp/views.py
from articleapp.models import Article
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect
from django.views.generic.list import MultipleObjectMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from accountapp.forms import AccountUpdateForm
from accountapp.decorators import account_ownership_required

# Create your views here.
# feature/authentication

has_ownership = [account_ownership_required, login_required]

# Class Based View
class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    # resverse_lazy : Class Based View 사용함
    # reverse : Function Based View 사용함
    success_url = reverse_lazy("accountapp:hello_world")
    template_name = "accountapp/create.html"


class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = "target_user"
    template_name = "accountapp/detail.html"

    paginate_by = 25

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(
            object_list=object_list, **kwargs
        )


# @method_decorator(login_required, "get")
# @method_decorator(login_required, "post")
# @method_decorator(account_ownership_required, "get")
# @method_decorator(account_ownership_required, "post")
@method_decorator(has_ownership, "get")
@method_decorator(has_ownership, "post")
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = "target_user"
    form_class = AccountUpdateForm
    success_url = reverse_lazy("accountapp:hello_world")
    template_name = "accountapp/update.html"

    # User Authentication
    # self == view 의미한다(AccountUpdateView)
    # def get(self, *args, **kwargs):
    #     if self.request.user.is_authenticated and self.get_object() == self.request.user:
    #         return super().get(*args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()
    #         # return HttpResponseRedirect(reverse("accountapp:login"))

    # def post(self, *args, **kwargs):
    #     if self.request.user.is_authenticated and self.get_object() == self.request.user:
    #         return super().post(*args, **kwargs)
    #     else:
    #         return HttpResponseForbidden()


# @method_decorator(login_required, "get")
# @method_decorator(login_required, "post")
# @method_decorator(account_ownership_required, "get")
# @method_decorator(account_ownership_required, "post")
@method_decorator(has_ownership, "get")
@method_decorator(has_ownership, "post")
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = "target_user"
    success_url = reverse_lazy("accountapp:login")
    template_name = "accountapp/delete.html"

accountapp/templates/accountapp/create.html
{% extends 'base.html' %} {% block content %} {% load bootstrap4 %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
  <div class="mb-4">
    <h4>SignUP</h4>
  </div>
  <form action="{% url 'accountapp:create' %}" method="POST">
    {% csrf_token%} {% bootstrap_form form %}

    <input type="submit" class="btn btn-dark rounded-pill col-4 mt-3" />
  </form>
</div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %} {% block content %} {% load bootstrap4 %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
  <div class="mb-4">
    <h4>Quit</h4>
  </div>
  <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="POST">
    {% csrf_token%}
    <input
      type="submit"
      class="btn btn-danger rounded-pill col-4 mt-3"
      value="탈퇴"
    />
  </form>
</div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %} {% block content %}
<div>
  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    {% comment %} <p>{{ target_user.date_joined }}</p> {% endcomment %}
    {% if target_user.profile %}
    <img src="{{target_user.profile.image.url}}" style="
        height: 12rem;
        width: 12rem;
        border-radius: 20rem;
        margin-bottom: 2rem;
        object-fit: cover;
      " />
    <h2 style="font-family: 'NanumSquareOTFBold'">
      {{ target_user.profile.nickname }}
      {% if target_user == user %}
      <a class="material-icons" href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
        style="text-decoration: none; color: black; box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;">
        edit
      </a>
      {% endif %}
    </h2>

    <h5 style="margin-bottom: 3rem;">
      {{target_user.profile.message}}
    </h5>
    {% else %}
    {% if target_user == user %}
    <a href="{% url 'profileapp:create' %}">
      <h2 style="font-family: 'NanumSquareOTFBold'">
        Create Profile
      </h2>
    </a>
    {% else %}
    <h2>
      닉네임 미설정
    </h2>
    {% endif %}
    {% endif %}

    {% if target_user == user %}
    <a class="material-icons" href="{% url 'accountapp:update' pk=user.pk %}"
      style="text-decoration: none; color: black; box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;">
      <p>
        settings
      </p>
    </a>
    <a class="material-icons" href="{% url 'accountapp:delete' pk=user.pk %}"
      style="text-decoration: none; color: black; box-shadow: 0 0 4px #fcc; border-radius: 10rem; padding: .4rem;">
      <p>cancel</p>
    </a>
    {% endif %}
  </div>
  <div>
    {% include 'snippets/list_fragment.html' with article_list=object_list %}
  </div>
</div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %} {% block content %} {% load bootstrap4 %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
  <div>
    <h4>Login</h4>
  </div>
  <div>
    <form action-="" method="POST">
      {%csrf_token%} {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-4 mt-3" />
    </form>
  </div>
</div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %} {% block content %} {% load bootstrap4 %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
  <div class="mb-4">
    <h4>Change Info</h4>
  </div>
  <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="POST">
    {% csrf_token%} {% bootstrap_form form %}

    <input type="submit" class="btn btn-dark rounded-pill col-4 mt-3" />
  </form>
</div>
{% endblock %}