articleapp/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from articleapp.views import (
    ArticleCreateView,
    ArticleDetailView,
    ArticleUpdateView,
    ArticleDeleteView,
    ArticleListView,
)

app_name = "articleapp"
urlpatterns = [
    # path("list/", TemplateView.as_view(template_name="articleapp/list.html"), name="list"),
    path("list/", ArticleListView.as_view(), name="list"),
    path("create/", ArticleCreateView.as_view(), name="create"),
    path("detail/<int:pk>", ArticleDetailView.as_view(), name="detail"),
    path("update/<int:pk>", ArticleUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", ArticleDeleteView.as_view(), name="delete"),
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from articleapp.views import ArticleListView

urlpatterns = [
    path("", ArticleListView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accountapp.urls")),
    path("profiles/", include("profileapp.urls")),
    path("articles/", include("articleapp.urls")),
    path("comments/", include("commentapp.urls")),
    path("projects/", include("projectapp.urls")),
    path("subscribes/", include("subscribeapp.urls")),
    # path("articles/", include("articleapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import include, path
from accountapp.views import (
    hello_world,
    AccountCreateView,
    AccountDetailView,
    AccountUpdateView,
    AccountDeleteView,
)
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accountapp"
urlpatterns = [
    path("hello_world/", hello_world, name="hello_world"),
    path("login/", LoginView.as_view(template_name="accountapp/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("create/", AccountCreateView.as_view(), name="create"),
    path("detail/<int:pk>", AccountDetailView.as_view(), name="detail"),
    path("update/<int:pk>", AccountUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", AccountDeleteView.as_view(), name="delete"),
]

articleapp/models.py
from django.db import models
from django.contrib.auth.models import User
from projectapp.models import Project

# Create your models here.
class Article(models.Model):
    writer = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name="article", null=True
    )
    project = models.ForeignKey(
        Project, on_delete=models.SET_NULL, related_name="article", null=True
    )

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to="article/", null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

templates/snippets/card.html
<div>
  <img src="{{ article.image.url }}" alt="" />
</div>

templates/snippets/card_project.html
<div style="display: block; text-align: center;text-decoration: none; ">
    <img src="{{ project.image.url }}" alt="" />
    <h5 class="mt-5" style="text-decoration: none; font-family: 'NanumSquareOTFBold';color: black;">
        {{ project.title | truncatechars:8 }}
    </h5>
</div>

templates/snippets/list_fragment.html
{% load static %} {% block content %}

<style>
    .container {
        padding: 0;
        margin: 0, auto;
    }

    .container a {
        width: 45%;
        max-width: 250px;
    }

    .container div {
        /* width: 250px; */
        /* background-color: antiquewhite; */
        display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 8px;
    }

    .container img {
        width: 100%;
        border-radius: 8px;
    }
</style>

{% if article_list %}
<div class="container">
    {% for article in article_list %}
    <a href="{% url 'articleapp:detail' pk=article.pk%}">
        {% include 'snippets/card.html' with article=article %}
    </a>
    {% endfor %}
</div>

<script src="{% static 'js/magicgrid.js' %}"></script>
{% else %}
<div style="text-align:center">
    <h1>No Article YET!!</h1>
</div>
{% endif %}

{% include 'snippets/pagination.html' with page_obj=page_obj%}

<div style="text-align: center">
    <a href="{% url 'articleapp:create' %}" class="btn btn-dark rounded-pill col-3 mt-3 mb-3 px-3">
        Create Article
    </a>
</div>
{% endblock %}

templates/snippets/pagination.html
<div style="text-align: center; margin: 1rem 0">
  {% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-secondary rounded-pill">
    {{ page_obj.previous_page_number }}
  </a>
  {% endif %}
  <a href="?page={{ page_obj.number }}" class="btn btn-secondary rounded-pill active">
    {{ page_obj.number }}
  </a>
  {% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}" class="btn btn-secondary rounded-pill active">
    {{ page_obj.next_page_number }}
  </a>
  {% endif %}
</div>