articleapp/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from articleapp.views import (
    ArticleCreateView,
    ArticleDetailView,
    ArticleUpdateView,
    ArticleDeleteView,
    ArticleListView,
)

app_name = "articleapp"
urlpatterns = [
    # path("list/", TemplateView.as_view(template_name="articleapp/list.html"), name="list"),
    path("list/", ArticleListView.as_view(), name="list"),
    path("create/", ArticleCreateView.as_view(), name="create"),
    path("detail/<int:pk>", ArticleDetailView.as_view(), name="detail"),
    path("update/<int:pk>", ArticleUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", ArticleDeleteView.as_view(), name="delete"),
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from articleapp.views import ArticleListView

urlpatterns = [
    path("", ArticleListView.as_view(), name="home"),
    path("admin/", admin.site.urls),
    path("accounts/", include("accountapp.urls")),
    path("profiles/", include("profileapp.urls")),
    path("articles/", include("articleapp.urls")),
    path("comments/", include("commentapp.urls")),
    path("projects/", include("projectapp.urls")),
    path("subscribes/", include("subscribeapp.urls")),
    # path("articles/", include("articleapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import include, path
from projectapp.views import ProjectCreateView, ProjectListView, ProjectDetailView

app_name = "projectapp"
urlpatterns = [
    path("list/", ProjectListView.as_view(), name="list"),
    path("create/", ProjectCreateView.as_view(), name="create"),
    path("detail/<int:pk>", ProjectDetailView.as_view(), name="detail"),
]

subscribeapp/urls.py
from subscribeapp.views import SubscriptionListView, SubscriptionView
from django.urls import include, path

app_name = "subscribeapp"
urlpatterns = [
    path("subscribe/", SubscriptionView.as_view(), name="subscribe"),
    path("list", SubscriptionListView.as_view(), name="list"),
]

urls.py
from django.urls import include, path
from accountapp.views import (
    hello_world,
    AccountCreateView,
    AccountDetailView,
    AccountUpdateView,
    AccountDeleteView,
)
from django.contrib.auth.views import LoginView, LogoutView

app_name = "accountapp"
urlpatterns = [
    path("hello_world/", hello_world, name="hello_world"),
    path("login/", LoginView.as_view(template_name="accountapp/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("create/", AccountCreateView.as_view(), name="create"),
    path("detail/<int:pk>", AccountDetailView.as_view(), name="detail"),
    path("update/<int:pk>", AccountUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", AccountDeleteView.as_view(), name="delete"),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
  {% include 'head.html' %}
  <body style="font-family: 'NanumSquareOTFRegular'">
    {% include 'header.html' %}
    <hr />
    {% block content %}{% endblock %}
    <hr />
    {% include 'footer.html' %}
  </body>
</html>

templates/footer.html
<div class="pragmatic_footer">
  <div class="pragmatic_footer_font_size">
    <span>공지사항</span> | <span>제휴문의</span> |
    <span>서비스 소개</span>
  </div>
  <div style="margin-top: 1rem" ;>
    <h6 class="pragmatic_logo">Pragmatic</h6>
  </div>
</div>

templates/head.html
{% load static %}

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <title>Pragmatic</title>
  <!-- BOOTSTRAP LINK -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
  <!-- GOOGLE FONT LINK -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Otomanopee+One&display=swap" rel="stylesheet" />

  <!-- LOAD GOOGLE MATERIAL ICON -->
  <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet" />

  <!-- LOAD CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}" />

  <style>
    @font-face {
      font-family: 'NanumSquareOTFBold',
      src: local('NanumSquareOTFBold'),
      url("{% static 'fonts/NanumSquareOTFBold.otf'%}") format("opentype");
    }

    @font-face {
      font-family: 'NanumSquareOTFExtraBold',
      src: local('NanumSquareOTFExtraBold'),
      url("{% static 'fonts/NanumSquareOTFExtraBold.otf'%}") format("opentype");
    }

    @font-face {
      font-family: 'NanumSquareOTFLight',
      src: local('NanumSquareOTFLight'),
      url("{% static 'fonts/NanumSquareOTFLight.otf'%}") format("opentype");
    }

    @font-face {
      font-family: 'NanumSquareOTFRegular',
      src: local('NanumSquareOTFRegular'),
      url("{% static 'fonts/NanumSquareOTFRegular.otf'%}") format("opentype");
    }
  </style>

  <!-- GOOGLE FONT LINK-->
  <!-- {% comment %}
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Pacifico&family=Varela+Round&display=swap"
    rel="stylesheet"
  />
  {% endcomment %} -->
</head>

templates/header.html
<div class="pragmatic_header">
  <div class="pragmatic_logo">
    <h1>Pragmatic</h1>
  </div>

  <div style="text-decoration: none;" class="prgmatic_header_navbar">
    <a href="{% url 'articleapp:list' %}" class="prgmatic_header_nav" style="text-decoration: none; color: black;">
      <span>Articles</span>
    </a>
    <a href="{% url 'projectapp:list' %}" class="prgmatic_header_nav" style="text-decoration: none; color: black;">
      <span>Projects</span>
    </a>
    <a href="{% url 'subscribeapp:list' %}" class="prgmatic_header_nav" style="text-decoration: none; color: black;">
      <span>Subscription</span>
    </a>
    {% if not user.is_authenticated %}
    <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="prgmatic_header_nav"
      style="text-decoration: none; color: black;"">
      <span>Login</span>
    </a>
    <a href=" {% url 'accountapp:create' %}?next={{ request.path }}" class="prgmatic_header_nav"
      style="text-decoration: none; color: black;">
      <span>SignUp</span>
    </a>
    {% else %}
    <a href="{% url 'accountapp:detail' pk=user.pk %}" class="prgmatic_header_nav"
      style="text-decoration: none; color: black;">
      <span>MyPage</span>
    </a>
    <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="prgmatic_header_nav"
      style="text-decoration: none; color: black;">
      <span>Logout</span>
    </a>
    {% endif %}
  </div>
</div>